### ISSUE TITLE
compilation errors on SLES11 sp4

### ISSUE THREAD

**Issue by Elwell** [cea-hpc/robinhood#56]
working with tarball robinhood-3.0-final on a sles11 sp4 box

automake-1.10.1-4.131.9.1.x86_64
autoconf-2.63-1.160.2.x86_64

```
aelwell@f001:~/compile$ tar zxvf ../robinhood-3.0-final.tar.gz
robinhood-3.0-final/
robinhood-3.0-final/.commit-template
robinhood-3.0-final/.gitignore
robinhood-3.0-final/COPYING
robinhood-3.0-final/ChangeLog
...
robinhood-3.0-final/web_gui/gui_v3/lang/sys.php
robinhood-3.0-final/web_gui/robinhood.conf
aelwell@f001:~/compile$ cd robinhood-3.0-final/
aelwell@f001:~/compile/robinhood-3.0-final$ sh autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `autotools'.
libtoolize: copying file `autotools/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `autotools/m4'.
libtoolize: copying file `autotools/m4/libtool.m4'
libtoolize: copying file `autotools/m4/ltoptions.m4'
libtoolize: copying file `autotools/m4/ltsugar.m4'
libtoolize: copying file `autotools/m4/ltversion.m4'
libtoolize: copying file `autotools/m4/lt~obsolete.m4'
configure:17702: error: possibly undefined macro: AM_DEFAULT_VERBOSITY
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

```
adding in  m4_pattern_allow([AM_DEFAULT_VERBOSITY]) to configure.ac still doesn't work:

```
aelwell@f001:~/compile/robinhood-3.0-final$ vim configure.ac
aelwell@f001:~/compile/robinhood-3.0-final$ sh autogen.sh
configure.ac:83: installing `autotools/compile'
configure.ac:79: installing `autotools/config.guess'
configure.ac:79: installing `autotools/config.sub'
configure.ac:18: installing `autotools/install-sh'
configure.ac:18: installing `autotools/missing'
src/cfg_parsing/Makefile.am: installing `autotools/depcomp'
configure.ac: installing `autotools/ylwrap'
automake: create_nostripe_OBJECTS should not be defined
src/tests/Makefile.am:12:   while processing program `create_nostripe'
automake: test_confparam_OBJECTS should not be defined
src/tests/Makefile.am:9:   while processing program `test_confparam'
automake: test_forcestripe_OBJECTS should not be defined
src/tests/Makefile.am:12:   while processing program `test_forcestripe'
automake: test_params_OBJECTS should not be defined
src/tests/Makefile.am:9:   while processing program `test_params'
automake: test_parse_OBJECTS should not be defined
src/tests/Makefile.am:9:   while processing program `test_parse'
automake: test_uidgidcache_OBJECTS should not be defined
src/tests/Makefile.am:9:   while processing program `test_uidgidcache'
autoreconf: automake failed with exit status: 1

```

Any ideas?
